### PR TITLE
Changed folder case to lowercase for uniformity.

### PR DESCRIPTION
**Pull request by tux-box**
Changing the folder names to lowercase for uniformity and better linux os support.. 
I did a rebase of the current upstream experimental branch before changing the case.
I'm still very new to git, I hope I did this correctly.

### CODE REVIEW

**Comment by rautamiekka** [comment]
Lazy evaluation should help performance, too.

**Comment by morgoth0** [comment]
> Lazy evaluation should help performance, too.

Not for this... it is just for linux to recognize files at load time. ARMA itself evaluates everything as lower case anyway no matter what you have it as other than explicit string comparisons

**Comment by tux-box** [comment]
> > Lazy evaluation should help performance, too.
> 
> Not for this... it is just for linux to recognize files at load time. ARMA itself evaluates everything as lower case anyway no matter what you have it as other than explicit string comparisons

I wish I understood Git better, I really do. For some reason copies of everything got pushed when they don't exist locally. I"m starting over.

**Comment by tux-box** [comment]
I redid the whole thing and submitted a new PR.
There were a lot of upstream stuff waiting to be dealt with, I went ahead and merged those before starting.
Figures crossed, I hope I didn't anger someone this time.

**Comment by morgoth0** [comment]
*Seems* okay to me, but it is late here ;)

**Comment by morgoth0** [comment]
But I for one, if the PR is clean, would have zero issues with making this change. Wouldn't cause any issues for Windows server owners and is cleaner for Linux server owners, so win-win

**Comment by rautamiekka** [comment]
> > Lazy evaluation should help performance, too.
> 
> Not for this... it is just for linux to recognize files at load time. ARMA itself evaluates everything as lower case anyway no matter what you have it as other than explicit string comparisons

Not for this, true, but overall.

> I wish I understood Git better, I really do. For some reason copies of everything got pushed when they don't exist locally. I"m starting over.

Yeah, I already quit trying to understand Git for its backwardness and the "Made a mistake ? That's your problem, no fixing allowed" design mentality.

**Comment by tux-box** [comment]
I probably should have mentioned this sooner, but I started over with PR: https://github.com/EpochModTeam/Epoch/pull/1026
Please post any further comments there.

**Pull request closed without merging**
