### PR TITLE
Reworked Building Script

### PR DESCRIPTION
**Pull request by Ignatz-HeMan**
- Added Vecorbuilding (with arrow keys by default)
- Added: Building element can be detached to walk around the Element before saving
- Added: With SHIFT / ALT you can control the steps of building placement while building
- Added: Help-Arrow to indicate door-opening direction
- Added: Max building height now will be checked direcly by building element placement
- Changed: Replaced 0/90/180/270° direction build mode with "Rotate 90°"
- Fixed: 90° and 270° Snap was broken
- Fixed: Sometimes Snapped elements rotate back on save

Credits:
The Base Vector Building Scripts comes from DirtySanchez from "DonkeyPunch Community Gaming Development Team".
Based on his Script, we reworked and fixed some more stuff in the building script together.

### CODE REVIEW

**Comment by ravmustang** [comment]
@Ignatz-HeMan 
Thanks for helping work out some bugs and for the pull merge request.
👍

**Comment by ReDBaroN1** [comment]
hey guys, fantastic work! 

Having a slight problem with this error:
`11:04:22 Error in expression <torResetObject", 0x4C]
];

_keyMap call EPOCH_custom_KeyMap;

switch (_args) do >
11:04:22   Error position: <EPOCH_custom_KeyMap;

switch (_args) do >
11:04:22   Error Undefined variable in expression: epoch_custom_keymap
11:04:22 File mpmissions\__CUR_MP.Altis\epoch_code\compile\setup\EPOCH_clientKeyMap.sqf, line 57
`
Any ideas?

**Comment by ravmustang** [comment]
@ReDBaroN1 sorry been out of town, am looking into this now

I did not find the 0x4c in the Epoch experimental source found here.
https://github.com/EpochModTeam/Epoch/blob/release/Sources/epoch_code/compile/setup/EPOCH_clientKeyMap.sqf

I think you might have used my script version instead. Let me know which and if cleared up or not.
Just getting back in town from a long work weekend.

-sTanG

**Comment by Ignatz-HeMan** [comment]
To get it work, you also have to add these changes:
https://github.com/EpochModTeam/Epoch/pull/754/files
So I think you are missing
Sources/epoch_code/customs/EPOCH_custom_KeyMap.sqf
or the changes in
https://github.com/EpochModTeam/Epoch/blob/experimental/Sources/epoch_config/Configs/CfgClientFunctions.hpp#L192

**Comment by ReDBaroN1** [comment]
Thanks guys, yes, I just followed the commit changes for this 757 and didn't see 754. Will add those now. Thanks :)

**Comment by ravmustang** [comment]
Thanks @Ignatz-HeMan , let us know how it goes @ReDBaroN1

**Comment by ReDBaroN1** [comment]
Thanks guys, that's put me error free. I like the new detach option so you can walk round and check how the object is looking. My only suggestion at this stage is that you can't continue to tilt/slant/ or move the object at all once it's snapped. In a perfect world, you would snap the object first so, it's clean to the other base object and then vector to the angle you want. I'm guessing this wouldn't be easy though as it would need to change it's centre point to the snapped edge.  (hope this makes sense...)

However, that said, and in agreement with He-Mans comments, in free mode this is extremely good. Well done guys :)

**Comment by ravmustang** [comment]
@ReDBaroN1 sorry that is actually how I had the script for arma 3 as base and for expoch. I do feel this can be done and should be done or re enabled....

Work week is almost over and I have some free time this weekend !

**Comment by ReDBaroN1** [comment]
OK cool! Just thought I would point it out, I still think it's great anyway... :)

**Pull request merged**
