### PR TITLE
remove }; 

### PR DESCRIPTION
**Pull request by ravmustang**
EDITED: corrects a rogue };

### CODE REVIEW

**Comment by ravmustang** [comment]
Please hold the merge for further debugging and possible commits.

THX

**Comment by vbawol** [comment]
I think this "};" was needed as it is used to close the while loop just after adding uiSleep 0.1;

```sqf
_build_sqf = _build_sqf + '
while {'+_condition+'} do {
	_tickTime = diag_tickTime;
';
```

```sqf
_build_sqf = _build_sqf + '
	uiSleep 0.1;
};';
```
For example this is an example what the final code should look like:
```sqf
while {true} do {
	_tickTime = diag_tickTime;
	// timer logic goes here
	uiSleep 0.1;
};
```

**Comment by vbawol** [comment]
Also, all that really is needed to add true to the end of the statement like this:

```sqf
'_cN = configName _x;if !(_cN in _lootClassesIgnore)then{_lootClasses pushBackUnique _cN}; true' configClasses _masterConfig;
```

**Comment by vbawol** [comment]
Got these changes merged with this commit: https://github.com/EpochModTeam/Epoch/commit/30d8107d75c94437a575d76086483664c2c1655f

**Pull request closed without merging**
