### PR TITLE
 Allow server devs to control accelerated HTA Loss

### PR DESCRIPTION
**Pull request by morgoth0**
Set a variable accelerateHTALoss in cfgEpochClient.hpp to specify whether the server's time acceleration should be applied to the rate of loss of Hunger, Thirst and Alcohol. Default is "true"

### CODE REVIEW

**Comment by Ignatz-HeMan** [comment]
This option is good, but a bit cleaner would be:

init:
_LossMultiplier = if (["CfgEpochClient", "accelerateHTALoss", true] call EPOCH_fnc_returnConfigEntryV2) then {timeMultiplier} else {1};

event2:
_hungerlossRate = _baseHungerLoss * _LossMultiplier;
_thirstlossRate = _baseThirstLoss * _LossMultiplier;
_alcoholLossRate = _baseAlcoholLoss * _LossMultiplier;

**Comment by morgoth0** [comment]
@Ignatz-HeMan That is a much better way of doing it. Still getting used to the language at the moment. Do you want to do a pull on that or should I do so? I think it would be better to use your code to be honest.

**Comment by Ignatz-HeMan** [comment]
Just do it ;)

**Comment by morgoth0** [comment]
Roger that

**Pull request closed without merging**
