### PR TITLE
Fix "throw items" from Fav-Bar

### PR DESCRIPTION
**Pull request by Ignatz-HeMan**

### CODE REVIEW

**Comment by raymix** [comment]
Looks great, could you please check if you can still load smoke shells into a rifle with GL muzzle?

**Comment by Ignatz-HeMan** [comment]
Okay, will Check it After Work and let you know

**Comment by Ignatz-HeMan** [comment]
Tested... 
Reload and throw, both works fine!

**Comment by raymix** [comment]
Thanks, man well done! :)

**Pull request merged**
