### PR TITLE
Safe/Load all Vehicle Magazines correctly

### PR DESCRIPTION
**Pull request by Ignatz-HeMan**
Set a help-variable (true) to differentiate between old/new saved entry

### CODE REVIEW

**Comment by Ignatz-HeMan** [comment]
Needs more tested! Found some problems

**Comment by vbawol** [comment]
was this ready to merge @Ignatz-HeMan? I seem to remember an email notification saying it was not ready yet, just want to be sure.

**Comment by Ignatz-HeMan** [comment]
Yep, we have it already running fine!
The E-Mail was a mistake (I thought, there was a problem, but wasn't)

**Comment by vbawol** [comment]
Nice, Thanks! got it merged.

**Pull request merged**
